### Проверка работоспособности и качества пайплайна

Здесь мы еще не запускаем никакое API, а загружаем модель (pipeline) напрямую и проверяем на отложенной (тестовой) выборке

In [1]:
import pandas as pd
from sklearn.metrics import roc_auc_score,roc_curve
import dill
dill._dill._reverse_typemap['ClassType'] = type

In [3]:
X_test = pd.read_csv("X_test.csv")
y_test = pd.read_csv("y_test.csv")

In [4]:
X_test.head(3)

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,70.0,0,582,0,40,0,51000.0,2.7,136,1,1,250,0
1,50.0,1,298,0,35,0,362000.0,0.9,140,1,1,240,0
2,45.0,0,2442,1,30,0,334000.0,1.1,139,1,0,129,1

In [6]:
with open('logreg_pipeline.dill', 'rb') as in_strm:
    pipeline = dill.load(in_strm)

In [7]:
predictions = pipeline.predict_proba(X_test.iloc[:500])
pd.DataFrame({'preds': predictions[:, 1]}).to_csv("test_predictions.csv", index=None)

In [8]:
roc_auc_score(y_score=predictions[:, 1][:], y_true=y_test.iloc[:500])

0.8621553884711779